# Generated by Django 2.0.3 on 2018-03-12 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0002_auto_20180312_0157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='media',
            managers=[
                ('images', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='like',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ighelper.Follower'),
        ),
    ]
