# Generated by Django 2.0.3 on 2018-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0003_auto_20180312_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='friend',
            field=models.BooleanField(default=False),
        ),
    ]
