# Generated by Django 2.0.3 on 2018-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0004_follower_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
