# Generated by Django 2.0.3 on 2018-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0006_auto_20180312_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='follower',
            name='instagram_id',
            field=models.BigIntegerField(),
        ),
    ]
