# Generated by Django 2.0.3 on 2018-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0007_auto_20180314_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='media',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
