# Generated by Django 2.0.3 on 2018-03-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0008_auto_20180316_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='text',
            new_name='caption',
        ),
    ]
