# Generated by Django 2.0.3 on 2018-03-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0009_auto_20180316_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='ighelper.Follower'),
        ),
    ]
