# Generated by Django 2.0.3 on 2018-03-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0010_auto_20180320_0102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='media',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
