# Generated by Django 2.0.3 on 2018-03-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0011_auto_20180322_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
