# Generated by Django 2.0.3 on 2018-03-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0012_auto_20180322_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='location',
            new_name='location_name',
        ),
    ]
