# Generated by Django 2.0.3 on 2018-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0013_auto_20180322_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
