# Generated by Django 2.0.3 on 2018-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0014_media_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_small',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
