# Generated by Django 2.0.3 on 2018-03-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0015_media_image_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='follower',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='name',
        ),
        migrations.AddField(
            model_name='follower',
            name='instagram_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ighelper.InstagramUser'),
            preserve_default=False,
        ),
    ]
