# Generated by Django 2.0.3 on 2018-03-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ighelper', '0016_auto_20180324_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='follower',
        ),
        migrations.AddField(
            model_name='like',
            name='instagram_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ighelper.InstagramUser'),
            preserve_default=False,
        ),
    ]
